import { app, BrowserWindow, shell } from 'electron';
import { IAppContainer } from 'interfaces';
import { getAssetPath } from 'main/utils/path-utils';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

export const createWindow = async (appContainer: IAppContainer) => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    show: false,
    width: 1024,
    height: 728,
    icon: getAssetPath('icon.png'),
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  mainWindow.on('close', event => {
    if (!mainWindow) {
      throw new Error('"mainWindow" is not defined');
    }

    if (appContainer.isQuitting) {
      return;
    }
    
    console.log("***Quit prevented")
        
    event.preventDefault();
    mainWindow.hide();
  })

  mainWindow.on('closed', () => {
    appContainer.mainWindow = null;
  });

  // Open urls in the user's browser
  mainWindow.webContents.setWindowOpenHandler((edata) => {
    shell.openExternal(edata.url);
    return { action: 'deny' };
  });
  
  if (!app.isPackaged) {
    // Open the DevTools.
    mainWindow.webContents.openDevTools();
  }

  return mainWindow;
};